name: path_to_purpose
description: "Its a global mentorship program."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  bcrypt: ^1.1.3

  # State Management
  flutter_riverpod: ^2.4.9

  # Database & Storage
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15  # Updated to match the new dependency
  flutter_secure_storage: ^9.0.0  # Secure user authentication storage
  shared_preferences: ^2.2.2  # Added for local storage
  
  # File Handling & Media
  file_picker: ^10.3.2  # For document and file selection
  image_picker: ^1.0.4  # For camera and gallery access
  permission_handler: ^12.0.1  # For handling permissions
  
  # UI Components
  cached_network_image: ^3.3.0  # For efficient image loading
  url_launcher: ^6.2.2  # For launching URLs and external links
  
  # Firebase (Commented out for now - uncomment when ready to use)
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
